"""second version

Revision ID: 745f9f109895
Revises: afc3fe873dd4
Create Date: 2023-06-05 12:00:18.779900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '745f9f109895'
down_revision = 'afc3fe873dd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('user_first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('user_second_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('user_fathers_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('user_role_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('user_password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('user_email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('user_birthday', sa.String(), nullable=False))
    op.add_column('users', sa.Column('user_registered', sa.TIMESTAMP(), nullable=True))
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['user_role_id'], ['id'])
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'name')
    op.drop_column('users', 'id')
    op.drop_column('users', 'registered')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('registered', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'user_registered')
    op.drop_column('users', 'user_birthday')
    op.drop_column('users', 'user_email')
    op.drop_column('users', 'user_password')
    op.drop_column('users', 'user_role_id')
    op.drop_column('users', 'user_fathers_name')
    op.drop_column('users', 'user_second_name')
    op.drop_column('users', 'user_first_name')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
